import numpy as np
import matplotlib.pyplot as plt
cm = plt.cm.get_cmap('RdYlBu_r')
sigma_vh = np.load('../data/data/mean_vh.npy')
sigma_vv = np.load('../data/data/mean_vv.npy')
incidence = np.load('../data/data/incident.npy')
wind_speed = np.load('../data/data/ten_wind.npy')
wind_direction = np.load('../data/data/wdir_relative.npy')

sigma_vh = sigma_vh[sigma_vv!=0]
incidence = incidence[sigma_vv!=0]
wind_speed = wind_speed[sigma_vv!=0]
wind_direction = wind_direction[sigma_vv!=0]
sigma_vv = sigma_vv[sigma_vv!=0]
sigma_vh = np.power(10, sigma_vh/10)
sigma_vv = np.power(10, sigma_vv/10)

vv_vh = sigma_vv - sigma_vh
dd = 10*np.log(np.sqrt(sigma_vv**2+sigma_vh**2))
vv_b_vh_b = (sigma_vv-0.7/1.7*sigma_vh) / (1.7 * sigma_vh)
sigma_nb = (sigma_vv - vv_b_vh_b*sigma_vh)/(1-vv_b_vh_b)
d = (sigma_vv-sigma_vh)/(0.3*sigma_vh)+1
z = (sigma_vv - d*sigma_vh)/(1-d)
plt.figure(figsize=(14, 10))
plt.subplot(3, 3, 1)
plt.scatter(wind_speed, sigma_vv, c = incidence)
plt.xlabel('wind_speed')
plt.ylabel('sigma_vv')
plt.colorbar()
plt.text(20, -7, 'incidence')
rms1 = np.corrcoef(wind_speed, sigma_vv)
print(rms1)
plt.text(15, -10, 'r=%f'%rms1[0, 1])
plt.subplot(3, 3, 2)
plt.scatter(wind_speed, vv_b_vh_b, c=incidence)
plt.xlabel('wind_speed')
plt.ylabel('vv_b/vh_b')
plt.text(20, 0.45, 'incidence(°)')
rms2 = np.corrcoef(wind_speed, vv_b_vh_b)
print(rms2)
plt.text(15, 0.3, 'r = %f'%rms2[0, 1])
plt.colorbar()
plt.subplot(3, 3, 3)
plt.scatter(wind_direction, sigma_vv, c=wind_speed, cmap=cm)
plt.xlabel('wind_direction')
plt.ylabel('sigma_vv')
plt.colorbar()
plt.text(370, -7, 'wind_speed')
plt.subplot(3, 3, 4)
plt.scatter(wind_direction, vv_b_vh_b, c=wind_speed, cmap=cm)
plt.text(370, 0.45, 'wind speed')
plt.xlabel('wind_direction')
plt.ylabel('vv_b/vh_b')
plt.colorbar()
plt.subplot(3, 3, 5)
plt.scatter(wind_speed, sigma_nb, c=incidence)
plt.xlabel('wind_speed')
plt.ylabel('sigma_nb')
plt.text(20, -7.5, 'incidence(°)')
plt.colorbar()
plt.subplot(3, 3, 6)
plt.scatter(wind_direction, sigma_nb, c=wind_speed, cmap=cm)
plt.xlabel('wind_direction')
plt.ylabel('sigma_nb')
plt.text(370, -7.5, 'wind_speed')
plt.colorbar()
plt.subplot(3, 3, 7)
plt.scatter(wind_speed, sigma_vh, c=incidence)
plt.xlabel('wind_speed')
plt.ylabel('sigma_vh')
plt.colorbar()
plt.text(20, -21,'incidence')
plt.subplot(3, 3,8)
plt.scatter(wind_direction, sigma_vh, c=wind_speed, cmap=cm)
plt.xlabel('wind_direction')
plt.ylabel('sigma_vh')
plt.text(370, -21, 'wind_speed')
plt.colorbar()
plt.subplot(3, 3,9)
plt.scatter(wind_direction, dd, c=incidence)

plt.savefig('analysis.eps')
